---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      shell:
        cmd: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

    - name: Install  kubelet kubeadm kubectl
      shell:
        cmd: |
          apt-get install -y apt-transport-https ca-certificates curl
          curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          apt-get update
          apt-get install -y kubelet kubeadm kubectl
          apt-mark hold kubelet kubeadm kubectl

    - copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
            "max-size": "100m"
            },
          "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json

    - name: Install  kubelet kubeadm kubectl
      shell:
        cmd: |
          systemctl enable docker
          systemctl daemon-reload
          systemctl restart docker

    - name: Tune sysconf
      shell:
        cmd: |
          echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf
          echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf
          echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
          echo "br_netfilter" >> /etc/modules
          echo "overlay" >> /etc/modules
