---
- hosts: master
  become: yes
  vars:
    - master_hostname: "k8s-master.local"
    - restart_host: true 
    - reset_cluster: true

  tasks:
    - set_fact:
        pod_cidr: "{{ lookup('file', 'terraform.tfvars')  | regex_search('pods_cidr_block.+=(.+)\".*', '\\1') | first | replace('\"','') | trim }}"

    - name: display the contents of the 'pod_cidr' variable
      debug:
        var: pod_cidr

    - name: Set hostname
      shell:
        cmd: |
          hostnamectl set-hostname  {{ master_hostname }}
          sed -i 's/127.0.0.1 localhost/127.0.0.1 localhost {{ master_hostname }}/' /etc/hosts

    - name: Wait for server to restart
      reboot:
        reboot_timeout: 3600
      when: restart_host|bool == true

    - name: Reset cluster
      command: "kubeadm reset --force"

    - name: Create cluster
      shell:
        cmd: |
          kubeadm init --pod-network-cidr={{ pod_cidr }}
          mkdir -p $HOME/.kube
          cp /etc/kubernetes/admin.conf $HOME/.kube/config
          chown $(id -u):$(id -g) $HOME/.kube/config
          export KUBECONFIG=/etc/kubernetes/admin.conf
          kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Create join token
      command: "kubeadm token create --print-join-command"
      register: join_cluster_command

    - local_action:
        module: copy
        content: "{{ join_cluster_command.stdout }}"
        dest: "{{ playbook_dir }}/join_cluster"
